(()=>{'use strict';
const $=s=>document.querySelector(s),canvas=$('#board'),ctx=canvas.getContext('2d'),KEY='liquidCats-infinite-v1';
const shapes={long:[[0,0],[1,0],[2,0]],short:[[0,0],[1,0]],square:[[0,0],[1,0],[0,1],[1,1]],el:[[0,0],[0,1],[1,1]]};
const names={long:'伸懶腰橘貓',short:'灰灰長貓',square:'團團三花',el:'彎彎黑白貓'};
function generate(forceChallenge=false,attempt=0){
 const challenge=forceChallenge||Math.random()<.55,w=challenge?5:4,h=challenge?5:4,o=new Set(),answer=[];
 function fill(){if(o.size===w*h)return true;let k=0;while(o.has(k))k++;const x=k%w,y=Math.floor(k/w);
 const options=Object.keys(shapes).flatMap(type=>[0,1,2,3].map(r=>({type,r}))).sort(()=>Math.random()-.5);
 for(const {type,r}of options){const c=cells(type,r);for(const [dx,dy]of c){const px=x-dx,py=y-dy;const keys=c.map(([a,b])=>(py+b)*w+px+a);if(!c.every(([a,b])=>px+a>=0&&px+a<w&&py+b>=0&&py+b<h)||keys.some(k=>o.has(k)))continue;keys.forEach(k=>o.add(k));answer.push({type,x:px,y:py,r});if(fill())return true;answer.pop();keys.forEach(k=>o.delete(k));}}return false}
 fill();
 const types=answer.map(p=>p.type).sort(()=>Math.random()-.5),level={w,h,blocked:[],walls:[],challenge,ruleVersion:3,types};
 if(challenge){
  const owner=Array(w*h);answer.forEach((p,i)=>cells(p.type,p.r).forEach(([x,y])=>owner[(p.y+y)*w+p.x+x]=i));
  const candidates=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++){const k=y*w+x;if(x<w-1&&owner[k]!==owner[k+1])candidates.push([k,k+1]);if(y<h-1&&owner[k]!==owner[k+w])candidates.push([k,k+w])}
  candidates.sort(()=>Math.random()-.5);for(const wall of candidates){level.walls.push(wall);if(level.walls.length>=5&&countSolutions(level,types,3)<=2)break}if(level.walls.length>14&&attempt<24)return generate(true,attempt+1)
 }
 return level;
}
const levels=[];
let index=0,pieces=[],selected=-1,rotation=0,hover=null,drag=null,moves=0,done=false,records={},saved={},images={},loaded=false,raf=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function cells(type,r){let a=shapes[type].map(p=>p.slice());for(let n=0;n<r;n++)a=a.map(([x,y])=>[-y,x]);const mx=Math.min(...a.map(p=>p[0])),my=Math.min(...a.map(p=>p[1]));return a.map(([x,y])=>[x-mx,y-my])}
function extent(c){return{w:Math.max(...c.map(p=>p[0]))+1,h:Math.max(...c.map(p=>p[1]))+1}}
function shapeKey(type,r){return cells(type,r).map(p=>p.join(',')).sort().join(';')}
function wallKey(a,b){return a<b?`${a}-${b}`:`${b}-${a}`}
function wallSet(level){return new Set((level.walls||[]).map(([a,b])=>wallKey(a,b)))}
function crossesWall(type,r,x,y,level,walls=wallSet(level)){const absolute=cells(type,r).map(([a,b])=>(y+b)*level.w+x+a),inside=new Set(absolute);for(const k of absolute){const cx=k%level.w,cy=Math.floor(k/level.w);if(cx<level.w-1&&inside.has(k+1)&&walls.has(wallKey(k,k+1)))return true;if(cy<level.h-1&&inside.has(k+level.w)&&walls.has(wallKey(k,k+level.w)))return true}return false}
function countSolutions(level,types,limit=3){
 const used=new Set((level.blocked||[]).map(([x,y])=>`${x},${y}`)),counts={},walls=wallSet(level);types.forEach(type=>counts[type]=(counts[type]||0)+1);let found=0,left=types.length,budget=150000;
 function visit(){if(found>=limit)return;if(!left){found++;return}let first=null;for(let y=0;y<level.h&&!first;y++)for(let x=0;x<level.w;x++)if(!used.has(`${x},${y}`)){first={x,y};break}if(!first)return;
  if(--budget<0){found=limit;return}for(const type of Object.keys(counts)){if(!counts[type])continue;const seen=new Set();for(let r=0;r<4;r++){const c=cells(type,r),shape=shapeKey(type,r);if(seen.has(shape))continue;seen.add(shape);for(const [dx,dy]of c){const x=first.x-dx,y=first.y-dy,keys=c.map(([a,b])=>`${x+a},${y+b}`);if(!c.every(([a,b])=>x+a>=0&&y+b>=0&&x+a<level.w&&y+b<level.h)||keys.some(k=>used.has(k))||crossesWall(type,r,x,y,level,walls))continue;keys.forEach(k=>used.add(k));counts[type]--;left--;visit();left++;counts[type]++;keys.forEach(k=>used.delete(k));if(found>=limit)return}}}
 }
 visit();return found;
}
function occupied(except=-1){const o=new Set();pieces.forEach((p,i)=>{if(i!==except&&p.x!==null)cells(p.type,p.r).forEach(([x,y])=>o.add(`${p.x+x},${p.y+y}`))});return o}
function blockers(l=levels[index]){return new Set((l.blocked||[]).map(([x,y])=>`${x},${y}`))}
function valid(id,x,y,r,o=occupied(id)){const l=levels[index],b=blockers(l),type=pieces[id].type;return !crossesWall(type,r,x,y,l)&&cells(type,r).every(([dx,dy])=>x+dx>=0&&y+dy>=0&&x+dx<l.w&&y+dy<l.h&&!b.has(`${x+dx},${y+dy}`)&&!o.has(`${x+dx},${y+dy}`))}
function save(){saved[index]={pieces,moves,done};try{localStorage.setItem(KEY,JSON.stringify({index,records,saved,levels}))}catch{}}
try{const s=JSON.parse(localStorage.getItem(KEY));if(s){records=s.records||{};saved=s.saved||{};(s.levels||[]).forEach((l,i)=>{if(l&&l.challenge&&l.ruleVersion!==3){levels.push(generate(true));delete saved[i];delete records[i]}else levels.push(l)});index=clamp(Number(s.index)||0,0,Math.max(0,levels.length-1))}}catch{}
function open(n,fresh=false){if(!levels[n])levels[n]=generate();index=n;const l=levels[n];pieces=l.types.map(type=>({type,x:null,y:null,r:0}));moves=0;done=false;selected=-1;rotation=0;hover=null;drag=null;if(!fresh&&saved[n]){const s=saved[n];if(Array.isArray(s.pieces)&&s.pieces.length===pieces.length){s.pieces.forEach((p,i)=>{if(p.type===pieces[i].type&&Number.isInteger(p.r)&&p.r>=0&&p.r<4&&Number.isInteger(p.x)&&Number.isInteger(p.y)&&valid(i,p.x,p.y,p.r))pieces[i]={...pieces[i],...p}});moves=Number(s.moves)||0;done=pieces.every(p=>p.x!==null)}}canvas.height=Math.round(600*l.h/l.w);$('#levels').value=n;$('#levelLabel').textContent=`無限紙箱 · 第 ${n+1} 箱${l.challenge?' · 挑戰箱':''}`;$('#message').textContent=l.challenge?'粗啡線係間隔；小貓可以轉身，但唔可以跨過。':'揀隻貓，再點紙箱放低；亦可以直接拖入去。';update();save();drawSoon()}
function update(){const count=pieces.filter(p=>p.x!==null).length;$('#progress').textContent=`${count} / ${pieces.length} 隻已入箱`;$('#moves').textContent=`${moves} 次擺放`;$('#rotate').disabled=selected<0||done;$('#complete').hidden=!done;$('#result').textContent=`${moves} 次擺放${records[index]?` · 最佳 ${records[index]} 次`:''}`;$('#next').textContent='下一個紙箱';$('#tray').innerHTML=pieces.map((p,i)=>`<button class="cat ${p.x!==null?'placed':''}" data-id="${i}" aria-label="${names[p.type]} ${i+1}${p.x!==null?'，已入箱':''}" aria-pressed="${selected===i}"><img src="../assets/liquid/${p.type}.webp" alt="" style="transform:rotate(${(selected===i?rotation:p.r)*90}deg)"><span>${p.x!==null?'✓':i+1}</span></button>`).join('');$('#levels').innerHTML=levels.map((l,i)=>`<option value="${i}" ${i===index?'selected':''}>紙箱 ${i+1}${l.challenge?' · 挑戰':''}${records[i]?' ✓':''}</option>`).join('')}
function select(id){if(done)return;if(pieces[id].x!==null){pieces[id].x=pieces[id].y=null;save()}selected=id;rotation=pieces[id].r;hover=null;$('#message').textContent=`${names[pieces[id].type]}：可以旋轉，再放入紙箱。`;update();drawSoon()}
function put(x,y){if(selected<0||done)return false;if(!valid(selected,x,y,rotation)){$('#message').textContent='呢度放唔落，試下旋轉或者換個位。';drawSoon();return false}pieces[selected]={...pieces[selected],x,y,r:rotation};moves++;selected=-1;hover=null;done=pieces.every(p=>p.x!==null);if(done){records[index]=records[index]?Math.min(records[index],moves):moves;$('#message').textContent='一隻都冇漏，全部裝好了！'}else $('#message').textContent='啱啱好！再揀下一隻。';update();save();drawSoon();return true}
function rotate(){if(selected<0||done)return;rotation=(rotation+1)%4;pieces[selected].r=rotation;update();save();drawSoon()}
function boardPos(e){const r=canvas.getBoundingClientRect(),l=levels[index];return{x:Math.floor((e.clientX-r.left)/r.width*l.w),y:Math.floor((e.clientY-r.top)/r.height*l.h),inside:e.clientX>=r.left&&e.clientX<r.right&&e.clientY>=r.top&&e.clientY<r.bottom}}
function at(x,y){return pieces.findIndex(p=>p.x!==null&&cells(p.type,p.r).some(([dx,dy])=>p.x+dx===x&&p.y+dy===y))}
$('#tray').addEventListener('pointerdown',e=>{const b=e.target.closest('[data-id]');if(!b||done)return;e.preventDefault();select(Number(b.dataset.id));drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};});
$('#tray').addEventListener('click',e=>{if(e.detail===0){const b=e.target.closest('[data-id]');if(b)select(Number(b.dataset.id))}});
canvas.addEventListener('pointerdown',e=>{if(done)return;e.preventDefault();const p=boardPos(e),id=at(p.x,p.y);if(id>=0||selected<0){if(id<0)return;select(id);drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false,fromBoard:true}}else{hover={x:p.x,y:p.y};drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false,placeTap:true}}drawSoon()});
window.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>6)drag.moved=true;const p=boardPos(e);hover=p.inside?{x:p.x,y:p.y}:null;drawSoon()});
window.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const p=boardPos(e),d=drag;drag=null;if(p.inside&&(d.moved||d.placeTap))put(p.x,p.y);else{hover=null;drawSoon()}});
window.addEventListener('pointercancel',()=>{drag=null;hover=null;drawSoon()});
canvas.addEventListener('keydown',e=>{if(done)return;if(e.key.toLowerCase()==='r'){e.preventDefault();rotate();return}if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))return;e.preventDefault();if(selected<0){const i=pieces.findIndex(p=>p.x===null);if(i>=0)select(i)}if(!hover)hover={x:0,y:0};if(e.key==='ArrowLeft')hover.x--;if(e.key==='ArrowRight')hover.x++;if(e.key==='ArrowUp')hover.y--;if(e.key==='ArrowDown')hover.y++;hover.x=clamp(hover.x,0,levels[index].w-1);hover.y=clamp(hover.y,0,levels[index].h-1);if(e.key===' ')put(hover.x,hover.y);drawSoon()});
function solve(){const l=levels[index],o=occupied(),b=blockers(l),remaining=pieces.map((p,i)=>p.x===null?i:-1).filter(i=>i>=0);let budget=150000;function visit(ids){if(!ids.length)return[];if(--budget<0)return null;let first;for(let y=0;y<l.h&&!first;y++)for(let x=0;x<l.w;x++)if(!b.has(`${x},${y}`)&&!o.has(`${x},${y}`)){first={x,y};break}const tried=new Set();for(const id of ids){const type=pieces[id].type;if(tried.has(type))continue;tried.add(type);const rotations=new Set();for(let r=0;r<4;r++){const c=cells(type,r),key=shapeKey(type,r);if(rotations.has(key))continue;rotations.add(key);for(const [dx,dy]of c){const x=first.x-dx,y=first.y-dy;if(!valid(id,x,y,r,o))continue;const keys=c.map(([a,b])=>`${x+a},${y+b}`);keys.forEach(k=>o.add(k));const rest=visit(ids.filter(i=>i!==id));keys.forEach(k=>o.delete(k));if(rest)return[{id,x,y,r},...rest]}}}return null}return visit(remaining)}
$('#hint').onclick=()=>{if(done)return;const answer=solve();if(!answer||!answer.length){$('#message').textContent='而家嘅擺法未能填滿，拎返一隻出嚟換個位試試。';return}const p=answer[0];select(p.id);rotation=p.r;hover={x:p.x,y:p.y};$('#message').textContent='呢隻貓可以放喺藍色位置；點一下嗰格放低。';drawSoon()};$('#rotate').onclick=rotate;$('#reset').onclick=()=>{if(!moves||confirm('重新砌呢個紙箱？已完成紀錄會保留。'))open(index,true)};$('#next').onclick=()=>open(index+1);$('#replay').onclick=()=>open(index,true);$('#levels').onchange=e=>{save();open(Number(e.target.value))};window.addEventListener('pagehide',save);
function drawCat(p,x,y,r,alpha=1){const c=cells(p.type,r),size=600/levels[index].w,b=extent(c),base=extent(shapes[p.type]);ctx.save();ctx.globalAlpha=alpha;ctx.beginPath();for(const [dx,dy]of c)ctx.rect((x+dx)*size,(y+dy)*size,size,size);ctx.clip();ctx.translate((x+b.w/2)*size,(y+b.h/2)*size);ctx.rotate(r*Math.PI/2);ctx.drawImage(images[p.type],-base.w*size/2,-base.h*size/2,base.w*size,base.h*size);ctx.restore()}
function draw(){if(!loaded)return;const l=levels[index],size=600/l.w;ctx.clearRect(0,0,600,canvas.height);for(let y=0;y<l.h;y++)for(let x=0;x<l.w;x++){ctx.fillStyle=(x+y)%2?'#e4c59f':'#edcfaa';ctx.fillRect(x*size,y*size,size,size);ctx.strokeStyle='#c6a078';ctx.lineWidth=2;ctx.strokeRect(x*size+1,y*size+1,size-2,size-2)}ctx.save();ctx.lineCap='round';for(const [a,b]of l.walls||[]){const ax=a%l.w,ay=Math.floor(a/l.w),bx=b%l.w,by=Math.floor(b/l.w);let x1,y1,x2,y2;if(ay===by){x1=x2=Math.max(ax,bx)*size;y1=ay*size+7;y2=(ay+1)*size-7}else{y1=y2=Math.max(ay,by)*size;x1=ax*size+7;x2=(ax+1)*size-7}ctx.strokeStyle='#684730';ctx.lineWidth=12;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.strokeStyle='#d7ad7e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}ctx.restore();pieces.forEach(p=>{if(p.x!==null)drawCat(p,p.x,p.y,p.r)});if(selected>=0&&hover){const good=valid(selected,hover.x,hover.y,rotation);for(const [x,y]of cells(pieces[selected].type,rotation)){ctx.fillStyle=good?'#568baa55':'#bf564d55';ctx.fillRect((hover.x+x)*size,(hover.y+y)*size,size,size)}drawCat(pieces[selected],hover.x,hover.y,rotation,.55)}}
function drawSoon(){if(!raf)raf=requestAnimationFrame(()=>{raf=0;draw()})}
open(index);Promise.all(Object.keys(shapes).map(type=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[type]=im;resolve()};im.onerror=reject;im.src=`../assets/liquid/${type}.webp`}))).then(()=>{loaded=true;drawSoon()}).catch(()=>{$('#message').textContent='小貓圖片未載入，請重新整理再試。'});
})();
