(()=>{'use strict';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),W=450,H=680,FLOOR=646,LINE=92;
const radii=[23,29,36,44,53,63,74,86,99],names=['小小瞌睡','捲捲橘貓','灰灰午睡','三花好夢','抱抱睡','攤攤眠','毛茸茸夢','雲朵熟睡','大大晚安'];
const shapes=[{x:.98,y:.73},{x:.98,y:.88},{x:.98,y:.82},{x:.98,y:.82},{x:.98,y:.90},{x:.98,y:.64},{x:.98,y:.86},{x:.98,y:.91},{x:.98,y:.89}];
const images=radii.map((_,i)=>{const im=new Image();im.src=`../assets/sleep/cat-${i+1}-clean.png`;return im});
let cats=[],particles=[],score=0,best=0,current=0,next=0,aim=210,cool=0,paused=false,ended=false,time=0,last=0,acc=0,sound=false,audio,warning=0;
try{best=Number(localStorage.getItem('catSleep-best'))||0}catch{}$('#best').textContent=best;
const random=()=>Math.floor(Math.random()*4),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function note(level){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=220*Math.pow(2,level/9);g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.25);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.26)}catch{}}
function updateScore(n){score+=n;best=Math.max(best,score);$('#score').textContent=score;$('#best').textContent=best;try{localStorage.setItem('catSleep-best',best)}catch{}}
function drawCat(c,x,y,r,angle=0,alpha=1){const im=images[c];ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(angle);if(im.complete&&im.naturalWidth)ctx.drawImage(im,-r,-r,r*2,r*2);ctx.restore()}
function preview(){const c=$('#next'),g=c.getContext('2d');g.clearRect(0,0,100,70);const im=images[next];if(im.complete&&im.naturalWidth)g.drawImage(im,18,3,64,64);c.setAttribute('aria-label',`下一隻：${names[next]}`)}
images.forEach(im=>im.onload=preview);
const radiusX=c=>c.r*shapes[c.l].x,radiusY=c=>c.r*shapes[c.l].y;
function reset(){cats=[];particles=[];score=0;current=random();next=random();cool=0;ended=false;paused=false;warning=0;$('#score').textContent=0;$('#overlay').hidden=true;preview()}
function drop(){if(paused||ended||cool>0)return;const r=radii[current],side=r*shapes[current].x;cats.push({l:current,x:clamp(aim,side+7,W-side-7),y:48,r,vx:0,vy:0,a:0,born:time,above:0});current=next;next=random();cool=.52;preview();note(0)}
function merge(a,b){const l=a.l,x=(a.x+b.x)/2,y=(a.y+b.y)/2;cats=cats.filter(c=>c!==a&&c!==b);if(l<8){const r=radii[l+1],side=r*shapes[l+1].x,bottom=r*shapes[l+1].y;cats.push({l:l+1,x:clamp(x,side+7,W-side-7),y:Math.min(y,FLOOR-bottom),r,vx:(a.vx+b.vx)/2,vy:-45,a:0,born:time,above:0})}updateScore(2**(l+2));for(let i=0;i<9;i++)particles.push({x,y,vx:(Math.random()-.5)*110,vy:-Math.random()*100,life:.7});note(l+2)}
function step(dt){if(paused||ended)return;time+=dt;cool=Math.max(0,cool-dt);for(const c of cats){c.vy+=590*dt;c.vx*=.995;c.x+=c.vx*dt;c.y+=c.vy*dt;c.a=clamp(c.vx*.002,-.25,.25)}
for(let iter=0;iter<8;iter++){for(const c of cats){const rx=radiusX(c),ry=radiusY(c);if(c.x<rx+7){c.x=rx+7;c.vx=Math.abs(c.vx)*.22}if(c.x>W-rx-7){c.x=W-rx-7;c.vx=-Math.abs(c.vx)*.22}if(c.y>FLOOR-ry){c.y=FLOOR-ry;c.vy=c.vy>12?-c.vy*.11:0;c.vx*=.88}}
let fused=false;outer:for(let i=0;i<cats.length;i++)for(let j=i+1;j<cats.length;j++){const a=cats[i],b=cats[j],dx=b.x-a.x,dy=b.y-a.y,sx=radiusX(a)+radiusX(b),sy=radiusY(a)+radiusY(b),nd=Math.hypot(dx/sx,dy/sy);if(nd>=1)continue;if(a.l===b.l&&time-a.born>.14&&time-b.born>.14){merge(a,b);fused=true;break outer}let gx=dx/(sx*sx),gy=dy/(sy*sy),gm=Math.hypot(gx,gy),nx=gm?gx/gm:1,ny=gm?gy/gm:0;const contact=1/Math.sqrt((nx*nx)/(sx*sx)+(ny*ny)/(sy*sy)),overlap=Math.max(0,contact-Math.hypot(dx,dy)),ia=1/(radiusX(a)*radiusY(a)),ib=1/(radiusX(b)*radiusY(b)),total=ia+ib;a.x-=nx*overlap*ia/total;a.y-=ny*overlap*ia/total;b.x+=nx*overlap*ib/total;b.y+=ny*overlap*ib/total;const rv=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rv<0){const impulse=-1.06*rv/total;a.vx-=impulse*ia*nx;a.vy-=impulse*ia*ny;b.vx+=impulse*ib*nx;b.vy+=impulse*ib*ny}a.vx*=.99;b.vx*=.99}if(fused)continue}
warning=0;for(const c of cats){if(time-c.born>1.8&&c.y-radiusY(c)<LINE){c.above+=dt;warning=Math.max(warning,c.above)}else c.above=0}if(warning>=3){ended=true;saveSession();$('#overlay').hidden=false;$('#result').textContent=`你疊出了 ${score} 分的好夢。`;$('#again').focus()}for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt}particles=particles.filter(p=>p.life>0)}
function render(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#f5efe3';ctx.fillRect(0,0,W,H);ctx.fillStyle='#e6eaf0';ctx.fillRect(0,0,W,LINE);ctx.strokeStyle=warning?'#c66b4c':'#b0a89b';ctx.lineWidth=1.5;ctx.setLineDash([5,6]);ctx.beginPath();ctx.moveTo(12,LINE);ctx.lineTo(W-12,LINE);ctx.stroke();ctx.setLineDash([]);ctx.font='14px system-ui';ctx.fillStyle=warning?'#a3472b':'#857b6e';ctx.textAlign='right';ctx.fillText(warning?`床快滿了 · ${Math.max(1,Math.ceil(3-warning))}`:'留一點空間給好夢',W-14,LINE-10);ctx.fillStyle='#a9c8d5';ctx.beginPath();ctx.roundRect(4,FLOOR,W-8,34,14);ctx.fill();ctx.strokeStyle='#537383';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(15,FLOOR+13);ctx.lineTo(W-15,FLOOR+13);ctx.stroke();if(!ended){const r=radii[current],side=r*shapes[current].x,x=clamp(aim,side+7,W-side-7);ctx.strokeStyle='#7697a266';ctx.setLineDash([3,7]);ctx.beginPath();ctx.moveTo(x,65);ctx.lineTo(x,FLOOR);ctx.stroke();ctx.setLineDash([]);drawCat(current,x,45,r,0,cool>0?.35:1)}for(const c of cats)drawCat(c.l,c.x,c.y,c.r,c.a);for(const p of particles){ctx.globalAlpha=p.life/.7;ctx.fillStyle='#dea64e';ctx.beginPath();ctx.arc(p.x,p.y,3,0,7);ctx.fill()}ctx.globalAlpha=1}
function frame(t){if(document.hidden){last=0;requestAnimationFrame(frame);return}if(!last)last=t;acc+=Math.min((t-last)/1000,.05);last=t;while(acc>=1/120){step(1/120);acc-=1/120}render();requestAnimationFrame(frame)}
function move(e){const rect=canvas.getBoundingClientRect();aim=clamp((e.clientX-rect.left)*W/rect.width,25,W-25)}
canvas.addEventListener('pointerdown',e=>{move(e);canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',e=>{move(e);drop()});canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' '].includes(e.key)){e.preventDefault();if(e.key===' ')drop();else aim=clamp(aim+(e.key==='ArrowLeft'?-15:15),25,W-25)}});$('#again').onclick=()=>{reset();saveSession();canvas.focus()};document.addEventListener('visibilitychange',()=>{last=0});reset();
function saveSession(){try{localStorage.setItem('catSleep-session-v1',JSON.stringify({cats,score,current,next,aim,time,ended,warning,worldW:W}))}catch{}}
try{const s=JSON.parse(localStorage.getItem('catSleep-session-v1'));if(s&&Array.isArray(s.cats)&&s.cats.every(c=>Number.isFinite(c.x)&&Number.isFinite(c.y)&&Number.isInteger(c.l)&&c.l>=0&&c.l<9)){const scale=W/(Number(s.worldW)||420);cats=s.cats.map(c=>({...c,x:clamp(c.x*scale,radiusX(c)+7,W-radiusX(c)-7)}));score=Number(s.score)||0;current=Math.max(0,Math.min(3,Number(s.current)||0));next=Math.max(0,Math.min(3,Number(s.next)||0));aim=clamp((Number(s.aim)||210)*scale,25,W-25);time=Number(s.time)||0;ended=!!s.ended;warning=Number(s.warning)||0;$('#score').textContent=score;$('#overlay').hidden=!ended;if(ended)$('#result').textContent=`你疊出了 ${score} 分的好夢。`;preview()}}catch{}
window.addEventListener('pagehide',saveSession);document.addEventListener('visibilitychange',()=>{if(document.hidden)saveSession()});document.querySelector('.game-home a')?.addEventListener('click',saveSession);requestAnimationFrame(frame);
})();
