(()=>{'use strict';const $=s=>document.querySelector(s),canvas=$('#board'),ctx=canvas.getContext('2d'),KEY='catBlocks-v1';
const shapes=[[[0,0]],[[0,0],[1,0]],[[0,0],[0,1]],[[0,0],[1,0],[2,0]],[[0,0],[0,1],[0,2]],[[0,0],[1,0],[0,1],[1,1]],[[0,0],[0,1],[1,1]],[[1,0],[0,1],[1,1]],[[0,0],[1,0],[1,1]],[[0,0],[1,0],[2,0],[3,0]],[[0,0],[0,1],[0,2],[0,3]],[[0,0],[1,0],[2,0],[1,1]],[[0,0],[1,0],[2,0],[0,1],[1,1],[2,1]],[[0,0],[1,0],[2,0],[0,1],[1,1],[2,1],[0,2],[1,2],[2,2]]];
let board=Array(64).fill(0),tray=[],score=0,best=0,selected=-1,hover=null,drag=null,over=false;const imgs=[];const colors=['#eab98b','#acc4ca','#d2c7aa'];
function save(){try{localStorage.setItem(KEY,JSON.stringify({board,tray,score,best}))}catch{}}
function deal(){return Array.from({length:3},()=>({cells:shapes[Math.floor(Math.random()*shapes.length)],color:1+Math.floor(Math.random()*3)}))}
function valid(p,x,y){return p&&p.cells.every(([a,b])=>x+a>=0&&x+a<8&&y+b>=0&&y+b<8&&!board[(y+b)*8+x+a])}
function hasMove(){return tray.some(p=>p&&Array.from({length:64},(_,i)=>i).some(i=>valid(p,i%8,Math.floor(i/8))))}
function cell(c,x,y,size,color,alpha=1){c.save();c.globalAlpha=alpha;c.fillStyle=colors[color-1];c.beginPath();c.roundRect(x+2,y+2,size-4,size-4,size*.14);c.fill();const im=imgs[color-1];if(im&&im.complete&&im.naturalWidth){const scale=size*.92/Math.max(im.naturalWidth,im.naturalHeight),w=im.naturalWidth*scale,h=im.naturalHeight*scale;c.drawImage(im,x+(size-w)/2,y+(size-h)/2,w,h)};c.restore()}
function draw(){ctx.clearRect(0,0,640,640);for(let i=0;i<64;i++){const x=i%8*80,y=Math.floor(i/8)*80;ctx.fillStyle=(i%8+Math.floor(i/8))%2?'#d5e1e2':'#e7eeeb';ctx.fillRect(x+1,y+1,78,78);if(board[i])cell(ctx,x,y,80,board[i])}if(selected>=0&&hover&&tray[selected]){const p=tray[selected],ok=valid(p,hover.x,hover.y);p.cells.forEach(([a,b])=>{const x=(hover.x+a)*80,y=(hover.y+b)*80;cell(ctx,x,y,80,p.color,.55);if(!ok){ctx.fillStyle='#b4545477';ctx.fillRect(x,y,80,80)}})}}
function render(){best=Math.max(best,score);$('#score').textContent=score;$('#best').textContent=best;$('#over').hidden=!over;$('#result').textContent=`今局 ${score} 分 · 最高 ${best} 分`;$('#tray').innerHTML=tray.map((p,i)=>`<button data-i="${i}" ${p?'':'disabled'} aria-label="${p?`第 ${i+1} 塊，${p.cells.length} 格`:'已放好'}" aria-pressed="${selected===i}"><canvas width="180" height="140"></canvas></button>`).join('');tray.forEach((p,i)=>{if(!p)return;const c=$(`#tray [data-i="${i}"] canvas`).getContext('2d'),w=Math.max(...p.cells.map(a=>a[0]))+1,h=Math.max(...p.cells.map(a=>a[1]))+1,s=Math.min(170/w,130/h);p.cells.forEach(([x,y])=>cell(c,(180-w*s)/2+x*s,(140-h*s)/2+y*s,s,p.color))});draw();save()}
function place(x,y){const p=tray[selected];if(over||!valid(p,x,y)){$('#message').textContent='呢度放唔落，試下另一個位。';return false}p.cells.forEach(([a,b])=>board[(y+b)*8+x+a]=p.color);score+=p.cells.length;tray[selected]=null;const rows=[],cols=[];for(let n=0;n<8;n++){if(board.slice(n*8,n*8+8).every(Boolean))rows.push(n);if(Array.from({length:8},(_,y)=>board[y*8+n]).every(Boolean))cols.push(n)}const clear=new Set();rows.forEach(y=>{for(let x=0;x<8;x++)clear.add(y*8+x)});cols.forEach(x=>{for(let y=0;y<8;y++)clear.add(y*8+x)});clear.forEach(i=>board[i]=0);const lines=rows.length+cols.length;score+=lines*10+Math.max(0,lines-1)*5;selected=-1;hover=null;if(tray.every(p=>!p))tray=deal();over=!hasMove();$('#message').textContent=lines?`消除 ${lines} 行／列！＋${lines*10+Math.max(0,lines-1)*5} 分`:'放好了！揀下一塊。';render();return true}
function fresh(){board=Array(64).fill(0);tray=deal();score=0;selected=-1;hover=null;over=false;$('#message').textContent='揀一塊，再點棋盤放低；亦可以拖入去。';render()}
function select(i){if(over||!tray[i])return;selected=i;hover=null;render()}
function pos(e){const r=canvas.getBoundingClientRect();return{x:Math.floor((e.clientX-r.left)/r.width*8),y:Math.floor((e.clientY-r.top)/r.height*8),inside:e.clientX>=r.left&&e.clientX<r.right&&e.clientY>=r.top&&e.clientY<r.bottom}}
$('#tray').addEventListener('pointerdown',e=>{const b=e.target.closest('[data-i]');if(!b||over||!tray[+b.dataset.i])return;e.preventDefault();select(+b.dataset.i);drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false}});$('#tray').addEventListener('click',e=>{const b=e.target.closest('[data-i]');if(b&&e.detail===0)select(+b.dataset.i)});
canvas.addEventListener('pointerdown',e=>{if(selected<0||over)return;e.preventDefault();const p=pos(e);hover=p;drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false,tap:true};draw()});window.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>6)drag.moved=true;const p=pos(e);hover=p.inside?p:null;draw()});window.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag,p=pos(e);drag=null;if(p.inside&&(d.tap||d.moved))place(p.x,p.y);hover=null;draw()});window.addEventListener('pointercancel',()=>{drag=null;hover=null;draw()});canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key)||over)return;e.preventDefault();if(selected<0)select(tray.findIndex(Boolean));hover=hover||{x:0,y:0};if(e.key==='ArrowLeft')hover.x=Math.max(0,hover.x-1);if(e.key==='ArrowRight')hover.x=Math.min(7,hover.x+1);if(e.key==='ArrowUp')hover.y=Math.max(0,hover.y-1);if(e.key==='ArrowDown')hover.y=Math.min(7,hover.y+1);if(e.key===' ')place(hover.x,hover.y);draw()});$('#restart').onclick=()=>{if(!score||confirm('開始新一局？最高分會保留。'))fresh()};$('#again').onclick=fresh;window.addEventListener('pagehide',save);
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.board)&&s.board.length===64&&s.board.every(n=>Number.isInteger(n)&&n>=0&&n<=3)&&Array.isArray(s.tray)&&s.tray.length===3){board=s.board;tray=s.tray;score=Number(s.score)||0;best=Number(s.best)||0}}catch{}if(!tray.length)tray=deal();over=!hasMove();render();['square','short','el'].forEach((name,i)=>{const im=new Image();imgs[i]=im;im.onload=render;im.src=`../assets/liquid/${name}.webp`});
})();
