(()=>{'use strict';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),W=400,H=580,R=14,KEY='catYarn-v1';
const blocks=[{x:186,y:278,w:30,h:140},{x:78,y:180,w:102,h:29},{x:271,y:395,w:65,h:27}];
const goal={x:310,y:111,r:35};const images={};let ball={x:88,y:480,vx:0,vy:0,a:0},shots=0,best=0,won=false,drag=null,history=[],moving=false,ready=false,sound=false,audio,raf=0,last=0,angle=-Math.PI/2,force=65,keyboard=false;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function save(){try{localStorage.setItem(KEY,JSON.stringify({ball,shots,best,won,history:history.slice(-50)}))}catch{}}
try{const s=JSON.parse(localStorage.getItem(KEY));if(s){best=Number(s.best)||0;if(s.ball&&Number.isFinite(s.ball.x)&&Number.isFinite(s.ball.y)){ball={x:clamp(s.ball.x,40,360),y:clamp(s.ball.y,44,536),vx:0,vy:0,a:Number(s.ball.a)||0};shots=Math.max(0,Number(s.shots)||0);won=!!s.won;history=Array.isArray(s.history)?s.history.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&Number.isFinite(p.shots)).slice(-50):[]}}}catch{}
function ui(){ $('#shots').textContent=shots;$('#best').textContent=best||'—';$('#undo').disabled=!history.length||moving;$('#win').hidden=!won;if(won)$('#result').textContent=`用了 ${shots} 桿。${shots<=3?'漂亮！小貓收到你的禮物了。':'下次試下用更少桿送到？'}`; }
function note(f=340){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.16)}catch{}}
function reset(){ball={x:88,y:480,vx:0,vy:0,a:0};shots=0;won=false;moving=false;drag=null;history=[];$('#message').textContent='拉住毛冷球向後拖，放手彈出去。';$('#power').style.width='0%';ui();save();wake()}
function shoot(dx,dy){const distance=Math.hypot(dx,dy);if(!ready||moving||won||distance<7)return;history.push({x:ball.x,y:ball.y,a:ball.a,shots});const power=Math.min(distance,110)*5.3;ball.vx=dx/distance*power;ball.vy=dy/distance*power;shots++;moving=true;drag=null;keyboard=false;$('#power').style.width='0%';$('#message').textContent='毛冷滾呀滾…';note(280);ui();save();wake()}
function reflect(nx,ny){const dot=ball.vx*nx+ball.vy*ny;if(dot<0){ball.vx-=1.72*dot*nx;ball.vy-=1.72*dot*ny;if(Math.abs(dot)>35)note(420)}}
function step(dt){ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.a+=ball.vx*dt/24;const friction=Math.exp(-.82*dt);ball.vx*=friction;ball.vy*=friction;
if(ball.x<39){ball.x=39;reflect(1,0)}if(ball.x>361){ball.x=361;reflect(-1,0)}if(ball.y<48){ball.y=48;reflect(0,1)}if(ball.y>532){ball.y=532;reflect(0,-1)}
for(const b of blocks){const cx=clamp(ball.x,b.x,b.x+b.w),cy=clamp(ball.y,b.y,b.y+b.h),dx=ball.x-cx,dy=ball.y-cy,d=Math.hypot(dx,dy);if(d<R&&d>0){const nx=dx/d,ny=dy/d;ball.x+=nx*(R-d);ball.y+=ny*(R-d);reflect(nx,ny)}}
if(Math.hypot(ball.x-goal.x,ball.y-goal.y)<goal.r){ball.vx=ball.vy=0;moving=false;won=true;best=best?Math.min(best,shots):shots;$('#message').textContent='小貓收到了，謝謝你！';note(660);ui();save();return}
if(Math.hypot(ball.vx,ball.vy)<9){ball.vx=ball.vy=0;moving=false;$('#message').textContent='再拉一下，試試借木塊反彈。';ui();save()}}
function sprite(name,x,y,w,h,rot=0){ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.drawImage(images[name],-w/2,-h/2,w,h);ctx.restore()}
function aim(){if(drag)return {dx:ball.x-drag.x,dy:ball.y-drag.y};if(keyboard)return{dx:Math.cos(angle)*force,dy:Math.sin(angle)*force};return null}
function draw(){if(!ready)return;ctx.clearRect(0,0,W,H);ctx.drawImage(images.rug,0,0,W,H);sprite('cat',goal.x,goal.y,111,115);sprite('fish',316,315,57,35,-.3);for(const b of blocks){if(b.h>b.w)sprite('wood',b.x+b.w/2,b.y+b.h/2,b.h,b.w,Math.PI/2);else sprite('wood',b.x+b.w/2,b.y+b.h/2,b.w,b.h)}
const target=aim();if(target&&!moving&&!won){const d=Math.hypot(target.dx,target.dy),len=Math.min(d,110),nx=target.dx/(d||1),ny=target.dy/(d||1);ctx.strokeStyle='#fff9ea';ctx.lineWidth=3;ctx.setLineDash([3,8]);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(ball.x,ball.y);ctx.lineTo(ball.x+nx*len*1.2,ball.y+ny*len*1.2);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();const ax=ball.x+nx*len*1.2,ay=ball.y+ny*len*1.2;ctx.moveTo(ax-nx*9-ny*5,ay-ny*9+nx*5);ctx.lineTo(ax,ay);ctx.lineTo(ax-nx*9+ny*5,ay-ny*9-nx*5);ctx.stroke();$('#power').style.width=`${len/110*100}%`}
sprite('ball',ball.x,ball.y,31,31,ball.a);if(!shots&&!target){ctx.strokeStyle='#fff8';ctx.lineWidth=2;ctx.setLineDash([4,6]);ctx.beginPath();ctx.arc(ball.x,ball.y,25,0,7);ctx.stroke();ctx.setLineDash([])}}
function frame(t){raf=0;const dt=last?Math.min((t-last)/1000,.04):1/60;last=t;if(moving&&!document.hidden){const n=Math.ceil(dt/(1/240));for(let i=0;i<n&&moving;i++)step(dt/n)}draw();if(moving&&!document.hidden)raf=requestAnimationFrame(frame);else last=0}
function wake(){if(!raf&&!document.hidden)raf=requestAnimationFrame(frame)}
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
canvas.addEventListener('pointerdown',e=>{if(!ready||moving||won)return;const p=pos(e);if(Math.hypot(p.x-ball.x,p.y-ball.y)>48){$('#message').textContent='先按住粉紅色毛冷球，再向後拉。';return}canvas.setPointerCapture(e.pointerId);drag={...p,id:e.pointerId};keyboard=false;wake()});
canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;drag={...pos(e),id:e.pointerId};wake()});
canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const p=pos(e);drag=null;shoot(ball.x-p.x,ball.y-p.y);$('#power').style.width='0%';wake()});
canvas.addEventListener('pointercancel',()=>{drag=null;$('#power').style.width='0%';wake()});
canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))return;e.preventDefault();if(moving||won||!ready)return;keyboard=true;if(e.key==='ArrowLeft')angle-=.12;if(e.key==='ArrowRight')angle+=.12;if(e.key==='ArrowUp')force=clamp(force+8,15,110);if(e.key==='ArrowDown')force=clamp(force-8,15,110);if(e.key===' ')shoot(Math.cos(angle)*force,Math.sin(angle)*force);wake()});
$('#undo').onclick=()=>{if(moving||!history.length)return;const p=history.pop();ball={x:p.x,y:p.y,a:p.a||0,vx:0,vy:0};shots=p.shots;won=false;drag=null;ui();save();wake();$('#message').textContent='返到上一桿，再試另一個角度。'};
$('#restart').onclick=()=>{if(!shots||confirm('重新開始呢一關？最佳紀錄會保留。'))reset()};$('#again').onclick=reset;$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'聲音 開':'聲音 關';$('#sound').setAttribute('aria-pressed',String(sound));$('#sound').setAttribute('aria-label',sound?'關閉聲音':'開啟聲音');note()};
document.addEventListener('visibilitychange',()=>{drag=null;last=0;save();if(document.hidden){if(raf)cancelAnimationFrame(raf);raf=0}else wake()});window.addEventListener('pagehide',save);
ui();Promise.all(['rug','ball','cat','wood','fish'].map(name=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[name]=im;resolve()};im.onerror=reject;im.src=`../assets/yarn/${name}.webp`}))).then(()=>{ready=true;$('#loading').hidden=true;wake()}).catch(()=>{$('#loading').innerHTML='<section><p>圖畫未載入成功。</p><button onclick="location.reload()">再載入一次</button></section>'});
})();
