(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),KEY='cingaryee-white-walk-v1';
const names=['燃燒的荊棘','風浪中的小船','橄欖葉與鴿子','展開的書卷','五餅二魚','同行的朋友'];
const verses=[['你腳上所站之地是聖地。','出埃及記 3:5','摩西看見荊棘燃燒，卻沒有燒毀，便轉過去看。神在那裏呼喚他。今天，你願意停下來聆聽嗎？','出埃及記 3:1–12'],['為甚麼膽怯？你們還沒有信心麼？','馬可福音 4:40','門徒在風浪中呼求耶穌，祂使風浪平靜。你可以坦誠地把甚麼懼怕帶到祂面前？','馬可福音 4:35–41'],['挪亞就知道地上的水退了。','創世記 8:11','鴿子帶回新擰下來的橄欖葉；挪亞仍等候，直到神吩咐他離開方舟。等待中，有甚麼微小的盼望？','創世記 8:6–19'],['主的靈在我身上。','路加福音 4:18','耶穌在拿撒勒會堂展開以賽亞書，宣告向貧窮人傳福音。這份好消息怎樣改變你看待身邊的人？','路加福音 4:16–21'],['我們在這裏只有五個餅，兩條魚。','馬太福音 14:17','門徒把有限的食物帶到耶穌面前，祂使眾人吃飽。你願意把甚麼有限的所有帶到主面前？','馬太福音 14:13–21'],['耶穌見他們的信心。','馬可福音 2:5','四個人抬著癱子來到耶穌面前，甚至拆開屋頂。這位貓朋友提醒我們：今天可以怎樣陪伴一個有需要的人？','馬可福音 2:1–12']];
const files=['walk-1','walk-2','sleep','bush','boat','dove','book','loaves','friend'],images={};
let ready=false,frame=0,last=0,down=false,previous=null,idle=0,dirty=false,saveTimer,raf=0;
let stored={};try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
let album=Array.isArray(stored.album)?stored.album.slice(0,12):[],seen=Array.isArray(stored.seen)?stored.seen.filter(n=>Number.isInteger(n)&&n>=0&&n<6):[];
function fresh(){return{path:[],cat:{x:115,y:365},cursor:0,objects:[],seeds:Array.from({length:6},(_,i)=>({x:90+Math.random()*420,y:100+i*92,type:i,found:false})),season:$('season').value,weather:$('weather').value,date:new Date().toLocaleDateString('zh-HK'),flip:false}}
function valid(s){return s&&Array.isArray(s.path)&&s.path.length<=8000&&s.path.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y))&&s.cat&&Number.isFinite(s.cat.x)&&Number.isFinite(s.cat.y)&&Array.isArray(s.seeds)&&s.seeds.length===6&&Array.isArray(s.objects)&&s.objects.length<=6&&Number.isInteger(s.cursor)&&s.cursor>=0&&s.cursor<=s.path.length}
let state=valid(stored.current)?stored.current:fresh();album=album.filter(valid);$('season').value=state.season;$('weather').value=state.weather;
function persist(){try{localStorage.setItem(KEY,JSON.stringify({current:state,album,seen}));dirty=false;return true}catch{$('message').textContent='這部裝置未能儲存；可以先下載小畫。';return false}}
function changed(){dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(persist,600)}
function counters(){$('count').textContent=album.length;$('found').textContent=`相遇 ${state.objects.length} / 6`;$('collection').textContent='相遇圖鑑：'+(seen.length?seen.map(i=>names[i]).join('、'):'還未遇見小東西。');$('save').disabled=state.path.length<2;$('storybuttons').replaceChildren();seen.forEach(i=>{const b=document.createElement('button');b.textContent=names[i];b.onclick=()=>{reflection(i);$('reflection').scrollIntoView({behavior:'smooth',block:'nearest'})};$('storybuttons').append(b)})}
function image(c,key,x,y,size,flip=false){const im=images[key];if(!im)return;const h=size*im.height/im.width;c.save();c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(im,-size/2,key.startsWith('walk-')?30-h:-h/2,size,h);c.restore()}
function render(c,s,t=0,snapshot=false){c.clearRect(0,0,600,700);c.fillStyle=s.weather==='夜'?'#e9edf3':({春:'#fffdf8',夏:'#f8fcfb',秋:'#fff9ef',冬:'#f6f8fb'}[s.season]||'#fffdf8');c.fillRect(0,0,600,700);
 c.strokeStyle=s.weather==='雨'?'#7c899055':'#302d28aa';c.lineWidth=s.weather==='雨'?7:3.5;c.lineCap='round';c.lineJoin='round';c.beginPath();s.path.forEach((p,i)=>{if(i===0)c.moveTo(p.x,p.y);else c.lineTo(p.x,p.y)});c.stroke();
 if(s.weather==='雨'){c.strokeStyle='#302d2866';c.lineWidth=2;c.stroke();}
 if(!snapshot)s.seeds.filter(o=>!o.found).forEach((o,i)=>{c.fillStyle='#c69b38';c.globalAlpha=.55+.25*Math.sin(t/850+i);c.font='24px serif';c.textAlign='center';c.fillText('✦',o.x,o.y);c.globalAlpha=1});
 s.objects.forEach(o=>image(c,files[o.type+3],o.x,o.y,o.type===5?77:60));
 const moving=s.cursor<s.path.length;image(c,!moving&&idle>3?'sleep':(moving&&Math.floor(t/240)%2?'walk-2':'walk-1'),s.cat.x,s.cat.y+(moving?Math.sin(t/120)*1.5:0),88,s.flip);
 if(!snapshot&&!s.path.length){c.fillStyle='#837967';c.font='18px system-ui';c.textAlign='center';c.fillText('從這裏，慢慢出發',300,575);c.font='15px system-ui';c.fillText('畫過微光，遇見一節經文',300,609)}
 if(snapshot){c.fillStyle='#68615b';c.font='16px system-ui';c.textAlign='left';c.fillText(`留白散步 · ${s.date} · ${s.season}日${s.weather}`,24,671)}
}
function reflection(type){const v=verses[type];$('verse').textContent='「'+v[0]+'」';$('reference').textContent=v[1]+' · 和合本節錄';$('thought').textContent=v[2];$('story').textContent='故事經文：'+v[3];$('reflection').hidden=false}
function tick(t){raf=0;if(document.hidden||!ready)return;const dt=Math.min((t-last)/1000||0,.05);last=t;let moving=state.cursor<state.path.length;
 if(moving){idle=0;let budget=dt*105;while(budget>0&&state.cursor<state.path.length){const target=state.path[state.cursor],dx=target.x-state.cat.x,dy=target.y-state.cat.y,d=Math.hypot(dx,dy);if(Math.abs(dx)>.2)state.flip=dx<0;if(d<=budget){state.cat={x:target.x,y:target.y};state.cursor++;budget-=d}else{state.cat.x+=dx/d*budget;state.cat.y+=dy/d*budget;budget=0}}
 state.seeds.forEach(o=>{if(!o.found&&Math.hypot(o.x-state.cat.x,o.y-state.cat.y)<48){o.found=true;state.objects.push({...o});if(!seen.includes(o.type))seen.push(o.type);reflection(o.type);$('message').textContent='遇見'+names[o.type]+'，停一停，讀一個故事。';counters();changed()}});if(state.cursor===state.path.length){changed();$('message').textContent=state.objects.length===6?'今天的相遇都在這張紙上了。可以收藏，或繼續走。':'小貓等你。再畫一段，或停下來歇一歇。'}}else idle+=dt;
 if(t-frame>32){render(ctx,state,t);frame=t}if(moving||down||idle<4)raf=requestAnimationFrame(tick);
}
function wake(){if(!raf&&!document.hidden){last=performance.now();raf=requestAnimationFrame(tick)}}
function point(e){const r=canvas.getBoundingClientRect();return{x:Math.max(25,Math.min(575,(e.clientX-r.left)/r.width*600)),y:Math.max(35,Math.min(635,(e.clientY-r.top)/r.height*700))}}
function add(p){if(state.path.length>=8000){$('message').textContent='這張紙走了很遠，收藏後再開一張吧。';return}const prev=state.path.at(-1)||state.cat;if(Math.hypot(p.x-prev.x,p.y-prev.y)<3)return;if(!state.path.length)state.path.push({...state.cat});state.path.push(p);changed();counters();idle=0;wake()}
canvas.addEventListener('pointerdown',e=>{if(!ready)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);down=true;previous=point(e);add(previous)});
canvas.addEventListener('pointermove',e=>{if(down){previous=point(e);add(previous)}});function release(){down=false;previous=null;changed();wake()}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
canvas.addEventListener('keydown',e=>{const d={ArrowLeft:[-18,0],ArrowRight:[18,0],ArrowUp:[0,-18],ArrowDown:[0,18]}[e.key];if(!d)return;e.preventDefault();const p=state.path.at(-1)||state.cat;add({x:Math.max(25,Math.min(575,p.x+d[0])),y:Math.max(35,Math.min(635,p.y+d[1]))})});
for(const id of ['season','weather'])$(id).addEventListener('change',()=>{state[id]=$(id).value;changed();render(ctx,state);wake()});
$('new').onclick=()=>{if(state.path.length>1&&!confirm('換一張新紙？未收藏的散步會被取代。'))return;state=fresh();idle=0;$('reflection').hidden=true;$('message').textContent='新的一張紙，今天想怎樣走？';counters();persist();render(ctx,state);wake()};
$('save').onclick=()=>{if(state.path.length<2)return;if(state.cursor<state.path.length){$('message').textContent='等小貓走完這一段，就可以收藏。';return}if(album.length>=12){showAlbum();$('dialogTitle').textContent='收藏已滿，先下載或刪除一幅';return}const copy=JSON.parse(JSON.stringify(state));if(album.some(x=>JSON.stringify(x.path)===JSON.stringify(copy.path)&&x.weather===copy.weather&&x.season===copy.season)){$('message').textContent='這一幅已收藏。再走一段，留下新的足跡。';return}album.unshift(copy);if(persist())$('message').textContent='已收藏在「散步小畫」。';counters()};
function showAlbum(){$('dialogTitle').textContent='散步小畫';$('gallery').replaceChildren();if(!album.length){const p=document.createElement('p');p.className='empty';p.textContent='還沒有小畫。走一段路，再按「收藏今日散步」。';$('gallery').append(p)}album.forEach((s,i)=>{const box=document.createElement('article');box.className='picture';const c=document.createElement('canvas');c.width=600;c.height=700;render(c.getContext('2d'),s,0,true);const p=document.createElement('p');p.textContent=s.date+' · '+s.season+'日'+s.weather+' · '+s.objects.map(o=>names[o.type]).join('、');const dl=document.createElement('button');dl.textContent='下載圖片';dl.onclick=()=>{const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='留白散步-'+(i+1)+'.png';a.click()};const del=document.createElement('button');del.textContent='刪除這幅';del.onclick=()=>{if(confirm('刪除這幅收藏？')){album.splice(i,1);persist();counters();showAlbum()}};box.append(c,p,dl,del);$('gallery').append(box)});if(!$('dialog').open)$('dialog').showModal()}
$('album').onclick=showAlbum;$('close').onclick=()=>$('dialog').close();document.addEventListener('visibilitychange',()=>{if(document.hidden){if(raf)cancelAnimationFrame(raf);raf=0;if(dirty)persist()}else{idle=0;wake()}});window.addEventListener('pagehide',()=>{if(dirty)persist()});
Promise.all(files.map(key=>new Promise(resolve=>{const im=new Image();im.onload=()=>{images[key]=im;resolve()};im.onerror=()=>resolve();im.src='../assets/walk/'+key+'.png'}))).then(()=>{ready=true;counters();render(ctx,state);if(state.objects.length)reflection(state.objects.at(-1).type);wake();if(Object.keys(images).length!==files.length)$('message').textContent='部分插畫未能載入，請重新整理再試。'});
})();
